### ISSUE TITLE
[dapps] tracker for DApp implementation V1

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#394]
## Feature / Issue
This is the tracker for the DApp (engine etc) implementation. When this issue is closed the DApps are implemented. 

## Tasks

* [x] [get an understanding of the custom renderer & about the VM](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/issues/393)
* [x] [Create the basic app layout for a DApp](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/issues/397)
* [ ] Create Development interface between computer and DApp engine
  * [UI](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/issues/398)
  * [panthalassa](https://github.com/Bit-Nation/panthalassa/issues/28)
* [ ] [Create Developer cli tools](http://399)
* [ ] [implement inner VM api](http://400)
* [ ] [implement renderer](http://401)
* [ ] VM utils(403)
