### ISSUE TITLE
[migration] migrate the app

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#446]
## Feature / Issue
Since we are moving our chat logic we will have to do some data migration. 

## Todo's
- [x] after login loading screen (#449)
- [x] move messages to Panthalassa and remove them and related models from Realm database
- [x] remove messages handling related methods from Pangea
- [x] implement fetching messages (present, coming and old ones) from Panthalassa
- [x] update the UI and interactions on chat screen (paging, etc)

**Comment by seland** [comment]
Done in 1.1.0
