### ISSUE TITLE
[migration] General migration screen

### ISSUE THREAD

**Issue by seland** [Bit-Nation/BITNATION-Pangea-mobile#449]
## Feature / Issue
We need to migrate some data from user account to Panthalassa. Generally, any other migration may be required in the future. Therefore, we need to create an infrastructure for that. 

### Todos
- [x] We need to add a new field `lastMigrationVersion` to the AccountSchema (check out [this document](https://github.com/florianlenz/pangea-specs/blob/schema-changes/client/database/index.md) for details). It should be a string with the version of the app which did the last migration. It should default to `0.0.0`. For example, after we did migration by our new release, it should be then changed to `1.1.0` for migrated account.
- [x] Create a migration screen component. There is no exact UI ready for that right now, but specification are - it should have some text (e.g. `Please wait, we are migrating your data`, check out [this](https://github.com/florianlenz/pangea-specs/blob/i18n/client/i18n/index.md) doc), loading indicator and default background (check out `src/components/common/BackgroundImage.js`). 
- [x] Create a logic to open the migration screen **after** login if migration is needed. The idea is to have something similar to database [linear migrations](https://realm.io/docs/javascript/latest#linear-migrations). It means, that we will have a list of migration functions with corresponding app version. Then, once login is done, we need to check the `lastMigrationVersion` of logged in account. Then we need to go through all migrations from `lastMigrationVersion` to current app version one-by-one and perform all of them. Suggestion is to have a separate `migrations` sagas that will handle migrations, open the migration screen and all other logic. For example on how we're using sagas, check out any folder of `src/sagas/`. Hint: we can listen for `CURRENT_ACCOUNT_ID_CHANGED` action that is called on login/logout (it can be used to show migration screen), we can listen for `SERVICES_CREATED` actions that is called when account related services are created (since migrations are likely require the services to be ready, it can be used to initiate migrations). Once migrations is done migration screen should be dismissed.
- [x] Modify account creation process to write the current app version into created account model (`src/sagas/accounts/sagas.js`).

## Acceptance criteria
- [x] Schema updated, login/create/edit account is working correctly.
- [x] Screen component is created and looks fine.
- [x] Migration sagas infrastructure is set up (without the migration implemented itself). Migration screen is opened correctly.
- [x] Tests 🙂

## Additional information
You will likely need [this library](https://github.com/rebeccahughes/react-native-device-info) to get current app version.
To open a screen you can add a new saga to `src/sagas/navigation/sagas.js`.
Keep in mind that the next release version will be 1.1.0 on both platforms (for details check out #448).

**Comment by florianlenz** [comment]
can we close this?

**Comment by seland** [comment]
Yes, closed by #453.
