### ISSUE TITLE
[accounts] Password recovery

### ISSUE THREAD

**Issue by seland** [Bit-Nation/BITNATION-Pangea-mobile#480]
## Feature / Issue
As a user I want to be able to login into my account in case I forgot my password. This can be done by entering private key (mnemonic). 

If the user cannot enter his password, then user can reset his password by first entering the 24-word mnemonic for the private key (i.e. 24 words). Once the private key is entered, user sets a password. 

The password can be the same as a previous password, unless @seland or @florianlenz disagrees. If a new password is required, then we have to check against all old passwords.

## Tasks
- [ ] UX: flow describing journey to reset password after logging into account with private key
- [ ] UI : Screen designs for reset password using private key entry

## Acceptance criteria
- [ ] Dev accepts UX design for the process
- [ ] Creative accepts UI screens for process
- [ ] UI coded
- [ ] Process coded
- [ ] QC: Check for mistakes, verify it works, try to break it, hack it

## Additional information
We likely will merge this functionality with existing one for restoring an account. 
Restoring an account will add the ability to recover the account data from an outside source, e.g. cloud or clipboard or local file.

**Comment by mimetic** [comment]
This concept is a restore functionality, but it requires having a way to backup your account first. We don't have that, so that is why this is on hold.

**Comment by seland** [comment]
@mimetic It's not about restore an account, it's about restore access to the existing account. So, in case user lost her password, there is a way to reset it using private key.

**Comment by mimetic** [comment]
@seland Oops, I you are right. I don't seem to have UX/UI for this yet.

**Comment by seland** [comment]
Done by #493.
