### ISSUE TITLE
[accounts] Merging of duplicates

### ISSUE THREAD

**Issue by seland** [Bit-Nation/BITNATION-Pangea-mobile#482]
## Feature / Issue
As a user I'm confused by having two separated accounts with the same keys (private, identity, wallet, etc). This happens because we didn't handle that case when recovering account.

## Todos
- [ ] Change a way of recovering so that the same account won't be created (instead will be logged in into existing one).
- [ ] Create UI design for choosing which account from duplicates should be kept (@mimetic)
- [ ] Implement UI and logic on Pangea.

## Acceptance criteria
- [ ] Duplicated user accounts are removed

## Additional information
It may be thought together with #480.

**Comment by hunght** [comment]
this will be done on Friday 24 August
