### ISSUE TITLE
[chat] Contacts logic 

### ISSUE THREAD

**Issue by seland** [Bit-Nation/BITNATION-Pangea-mobile#510]
## Feature / Issue
We need to add functionality of storing contacts. Contact is a profile of person that we can have a chat with (now or later). Contacts list will be stored on Panthalassa. We can work with them using `PanthalassaCall` method with specific commands. Please check how DocumentsService is implemented for more details regarding `PanthalassaCall`. Contacts will be the same, but will just have `ALL` and `CREATE` commands.
Keep in mind that on Panthalassa side contacts will be stored as simply identityKey, so you don't need to pass the whole profile there. However, you should make sure that all contacts profiles are present on the database, i.e. don't ask Panthalassa to store contact before you have profile for it.

### Todo:
- [ ] Create ContactsService that will interact with Panthalassa (methods are not available at the moment, so you can just mock it to return some values, they will be provided soon).
- [ ] Implement action handling in contacts reducer (Take a look at the actions at `src/actions/contacts.js`)
- [ ] Implement sagas for interaction with ContactsService for fetching and creating contacts. Keep in mind that on Panthalassa side contacts will be stored as simply identityKey, so you need to map values correctly when you pass them back and forth. You can use `GET_PROFILE ` action to get profile by identity key.
- [ ] Specific case is `ADD_CONTACT` action - it should work as follows:
 - Take identity key and get profile with that key (using `GET_PROFILE` action).
 - If profile fetched successfully, then contact should be sent to Panthalassa to add to contacts list.
 - If profile fetch failed, contact should not be stored and error should be returned to callback
 - When contact saving finished call callback with appropriate result.
 - Be sure to call callback in each logical branch of the method.
- [ ] Tests for action, reducer and sagas.

## Acceptance criteria
- [ ] All todos are finished.

## Additional information
There is a basic structure already set up for contacts actions, reducer and types. You like won't need to add new actions.

**Comment by prameetc** [comment]
@kevowevo This can be completed by 15th Sep i.e in a week.

**Comment by seland** [comment]
@kevowevo I'll be second assignee on that task to assist @prameetc. Together we will complete it by 12th Sep.

**Comment by seland** [comment]
Closed by #514.
