### ISSUE TITLE
[nation] implementation tracker

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#99]
## Feature / Issue
As a user I should be able to create and join / leave nations. 

## Acceptance criteria
- [x] create an nation
   - all fields are required
- [x] list my nation's (those that I created)
- [x] join a nation
- [x] leave an nation
- [x] check if you 

## Additional information
- Have a look at the [Nation Schema](http://bitnation-pangea-libs.readthedocs.io/en/develop/schemata/#nationschema)

**Comment by Fernandomolica** [comment]
Thanks

Em 24 de jan de 2018 9:15 PM, "Florian Lenz" <notifications@github.com>
escreveu:
